<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://www.orderProcess.com/orderdetails" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://www.products.com/Inventory/Design" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://www.orderProcess.com/orderdetails/Ankit_Assigment_App/OrderProcessing/OrderProcessingBPELProcess"
                xmlns:ns1="http://xmlns.oracle.com/Ankit_Assigment_App/BillingSystem/BillingSystemBPELProcess">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/OrderProcessingBPELProcess.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://www.orderProcess.com/orderdetails"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://fmwctsap.ad.ea.com:7777/soa-infra/services/default/BillingSystem!1.0/WSDLs/BillingSystemBPELProcess.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://www.products.com/Inventory/Design"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [SAT MAR 17 20:43:49 IST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:InputParameters>
         <tns:Product_Info>
            <tns:Order_ID>
               <xsl:value-of select="/ns0:InputParameters/ns0:OrderDetails/ns0:Order_ID"/>
            </tns:Order_ID>
            <tns:Cust_ID>
               <xsl:value-of select="/ns0:InputParameters/ns0:OrderDetails/ns0:Cust_Info/ns0:Cust_ID"/>
            </tns:Cust_ID>
            <xsl:for-each select="/ns0:InputParameters/ns0:OrderDetails/ns0:Item_Info">
               <tns:Item>
                  <tns:Item_Name>
                     <xsl:value-of select="ns0:Item_Name"/>
                  </tns:Item_Name>
                  <tns:Item_Cost>
                     <xsl:value-of select="ns0:Item_Cost"/>
                  </tns:Item_Cost>
               </tns:Item>
            </xsl:for-each>
         </tns:Product_Info>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>
